site_name: Test docs
site_description: "A docs test"
site_author: "Michael Hausenblas"
docs_dir: docs/
repo_name: "mhausenblas/mkdocs-template"
repo_url: "https://github.com/mhausenblas/mkdocs-template"
nav:
  - Home: index.md
  - DB: sql_vs_no_sql.md
  - 'Session 1' : introduction_to_web_apps_crud_rest_apis.md
theme:
  name: "material"
