site_name: Build a ML app
site_description: "A docs test"
site_author: "Ashit, Aritra, Pragyan"
docs_dir: docs/
repo_name: "pandalearnstocode/buildamlapp"
repo_url: "https://github.com/pandalearnstocode/buildamlapp"
nav:
  - 'Home': index.md
  - 'Web app & APIs' : introduction_to_web_apps_crud_rest_apis.md
theme:
  name: "material"
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
plugins:
  - mkdocs-video:
      css_style:
        width: "80%"
        height: "30.172vw"
