site_name: Build a ML app
site_description: "A docs test"
site_author: "Ashit, Aritra, Pragyan"
docs_dir: docs/
repo_name: "pandalearnstocode/buildamlapp"
repo_url: "https://github.com/pandalearnstocode/buildamlapp"
nav:
  - 'Home': index.md
  - 'Web app, REST APIs & setup' : 01_introduction_to_web_apps_crud_rest_apis.md
  - 'Documentation' : 02_documentation.md
theme:
  name: "material"
  features:
    - content.code.annotate
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
plugins:
  - mkdocs-video:
      css_style:
        width: "80%"
        height: "30.172vw"
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
